services:
  # テスト実行サービス
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      # カバレッジレポートをホスト側に出力
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=xml --cov-report=html

  # ユニットテストのみ
  test-unit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      # カバレッジレポートをホスト側に出力
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run pytest tests/unit/ -v --cov=src --cov-report=term-missing --cov-report=xml --cov-report=html

  # 統合テストのみ
  test-integration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run pytest tests/integration/ -v

  # Lintチェック
  lint:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lint
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../.flake8:/app/.flake8
    environment:
      - PYTHONUNBUFFERED=1

  # Blackフォーマット
  black:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lint
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    command: poetry run black --check --diff src/ tests/

  # Flake8
  flake8:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lint
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../.flake8:/app/.flake8
    command: poetry run flake8 src/ tests/ --count --statistics --show-source

  # MyPy
  mypy:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lint
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    command: poetry run mypy src/ --ignore-missing-imports --show-error-codes

  # Blackフォーマット適用（書き込み権限必要）
  format:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lint
    volumes:
      # フォーマット適用のため、ソースコードをマウント
      - ../src:/app/src
      - ../tests:/app/tests
    command: poetry run black src/ tests/

  # アプリケーション実行（開発用）
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      # アプリケーション実行時はソースコードとデータをマウント
      - ../src:/app/src
      - ../data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: poetry run python src/main.py
