name: CI - ユニット・統合テスト

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v4
    
    - name: Python 3.13 のセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Poetryのインストール
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Poetry依存関係のキャッシュ
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-3.13-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-3.13-
    
    - name: システム依存関係のインストール (OpenCV用)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: 依存関係のインストール
      timeout-minutes: 10
      run: |
        poetry install --no-interaction --no-ansi -vv
    
    - name: 単体テストの実行
      run: |
        poetry run pytest tests/unit/ -v --cov=src --cov-report=term-missing --cov-report=xml --cov-report=html
    
    - name: 統合テストの実行
      run: |
        poetry run pytest tests/integration/ -v
    
    - name: カバレッジレポートのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          htmlcov/
          coverage.xml
    
    - name: カバレッジバッジの更新 (codecov)
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true

